### ISSUE TITLE
сразу отключать юзерa если  введен неправильный пароль

### ISSUE THREAD

**Issue by rxxxt** [Dmi3Iva/IRC#49]

**Comment by Dmi3Iva** [comment]
Жду ответа https://21born2code.slack.com/archives/C02CAQGARC1/p1643119794077500

**Comment by Dmi3Iva** [comment]
Варианты из слака:
* отключаем после введения всех 3-х команд
* kill him

Думаю мы должны сразу отключать юзера. Добавлю это как часть задачи Quit
